export const GET_HOME_DATA = 'GET_HOME_DATA'
export const UPSERT_BUCKET = 'CREATE_BUCKET'
export const UPDATE_TODO = 'UPDATE_TODO'
export const CREATE_TODO="CREATE_TODO"
export const DELETE_TODO="DELETE_TODO"

// export const USER_SIGN_UP = 'USER_SIGN_UP'
// export const GET_USER_AND_DEPT_DETAILS = 'GET_USER_AND_DEPT_DETAILS'
// export const GET_LOGIN_USER_DETAILS = 'GET_LOGIN_USER_DETAILS'
// export const SEND_REQUEST = 'SEND_REQUEST'
// export const GET_REQUEST_DETAILS = 'GET_REQUEST_DETAILS'
// export const GET_ALL_DEPT = "GET_ALL_DEPT"
// export const SET_USER_LOGIN_ERROR_DETAILS = 'SET_USER_LOGIN_ERROR_DETAILS'
// export const UPDATE_REQ='UPDATE_REQ'